### ISSUE TITLE
您好，非常好的工作，谢谢作者的贡献，我想请教一下学生自我提升干预（Self-Improvement (Q6)）的这个步骤怎么实现？

### ISSUE THREAD

**Issue by zjj1333** [lswhim/CDM_ILOG#1]
![image](https://github.com/ECNU-ILOG/QCCDM/assets/38657581/ce3ee5a5-5128-467f-a5d2-ed616ea604be)
精读了改论文，论文创新点创新度很高，值得我们好好学习
但是对论文中的Self-Improvement (Q6)部分了解的不是很多，结合代码看了一下，但是代码中只有图中过程出现过，对这个过程很感兴趣，想请教作者怎么实现这块的工作，谢谢您！

**Comment by lswhim** [comment]
非常感谢您对我们工作的认可！由于时间有点久远，如果解释地不是很正确，还望您海涵！如果您仍有问题欢迎继续提问，或者直接邮件我shuoliu@stu.ecnu.edu.cn

这一部分是在QCCDM训练完成之后，我们对某一个学生Math2上的某一个学生进行硬干预，印象中是对计算机能力这个根节点的能力变成0.8，然后再经过因果结构方程模型，这个0.8会影响因果图上的节点，得到一个全新的能力值，也就是学生经过干预之后的能力。这就得到了第一个雷达图。

分别使用两次能力去使用训练好的QCCDM去预测学生在16个题目上的表现就得到了第二个热力图。
